# Generated by Django 4.1.7 on 2024-03-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudio_socio_economico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.solicitante'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='elemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudio_socio_economico.elemento'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio_socio_economico.seccion'),
        ),
        migrations.AddField(
            model_name='ropcionmultiple',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudio_socio_economico.opcion'),
        ),
        migrations.AddField(
            model_name='rdesplegable',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudio_socio_economico.opcion'),
        ),
        migrations.AddField(
            model_name='rcasillas',
            name='respuesta',
            field=models.ManyToManyField(blank=True, to='estudio_socio_economico.opcion'),
        ),
    ]
