# Generated by Django 4.1.13 on 2024-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_creacion_SiteColor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecolor',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sitecolor',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
