# Generated by Django 4.1.13 on 2024-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_sitecolor_options_alter_sitecolor_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
