# Generated by Django 4.1.13 on 2024-05-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_crear_cache_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecolor',
            old_name='name',
            new_name='nombre',
        ),
    ]
