# Generated by Django 4.1.7 on 2023-07-01 07:06

from django.db import migrations, models
import django.db.models.deletion
import solicitudes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(default='Ene-Jun 2023', editable=False, max_length=50)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidad')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'unique_together': {('modalidad', 'solicitante')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=solicitudes.models.documentoMediaPath, validators=[solicitudes.models.validador_pdf])),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.documento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Documento de Respuesta',
                'verbose_name_plural': 'Documentos de Respuesta',
                'unique_together': {('solicitud', 'documento')},
            },
        ),
    ]
