# Generated by Django 4.1.7 on 2024-03-04 20:38

from django.db import migrations, models
import django.db.models.deletion
import solicitudes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=solicitudes.models.documentoMediaPath, validators=[solicitudes.models.validador_pdf, solicitudes.models.validate_file_size])),
                ('estado', models.CharField(choices=[('pendiente', 'Revisión pendiente'), ('aprobado', 'Aprobado'), ('denegado', 'Denegado')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Documento de Respuesta',
                'verbose_name_plural': 'Documentos de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(default='Enero - Junio 2024', editable=False, max_length=50)),
                ('estado', models.CharField(choices=[('docRevicion', 'Documentación en revisión'), ('docError', 'Documentación erronea'), ('docAprobada', 'Documentación aprobada'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='docRevicion', max_length=20)),
                ('puntaje', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('renovacion', 'Renovación'), ('ingreso', 'Nuevo Ingreso')], default='ingreso', max_length=20)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidad')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-puntaje', '-id'],
            },
        ),
    ]
