# Generated by Django 4.1.7 on 2024-05-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0003_crear_Ciclo_y_campos_FK_temporales'),
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='ciclo_FK',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modalidades.ciclo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ciclo',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
