# Generated by Django 4.1.7 on 2024-05-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0007_renombrar_campos_ciclo_nuevos'),
        ('usuarios', '0001_initial'),
        ('solicitudes', '0005_eliminar_campos_ciclo_originales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='ciclo_FK',
            new_name='ciclo',
        ),
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together={('modalidad', 'ciclo', 'solicitante')},
        ),
    ]
