# Generated by Django 4.1.7 on 2024-05-06 19:35

from django.db import migrations, models
import django.db.models.deletion
import modalidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0007_renombrar_campos_ciclo_nuevos'),
        ('solicitudes', '0006_renombrar_campos_ciclo_nuevos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ciclo',
            field=models.ForeignKey(default=modalidades.models.ciclo_actual_pk, on_delete=django.db.models.deletion.CASCADE, to='modalidades.ciclo'),
        ),
    ]
