# Generated by Django 4.1.7 on 2024-05-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0002_convocatoria_config_pdf_y_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Enero - Junio 2024', max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='ultimo_ciclo_publicado_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modalidades.ciclo', verbose_name='Ultimo ciclo publicado'),
        ),
    ]
