# Generated by Django 4.1.7 on 2024-05-06 17:27

from django.db import migrations, models
import modalidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0003_crear_Ciclo_y_campos_FK_temporales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(default=modalidades.models.ciclo_actual_genNombre, max_length=100),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
