# Generated by Django 4.1.7 on 2024-05-06 17:27
from django.db import migrations

def obtener_mes_numero(mes):
    meses = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
    return meses.index(mes) + 1

def ordenar_lista_ciclos(registros):
    return sorted(registros, key=lambda x: (int(x.split()[-1]), obtener_mes_numero(x.split()[0])))

def migrarDatosdeCiclos(apps, schema_editor):
    Ciclo = apps.get_model('modalidades', 'Ciclo')
    Convocatoria = apps.get_model('modalidades', 'Convocatoria')
    Solicitud = apps.get_model('solicitudes', 'Solicitud')
    convocatoria = Convocatoria.objects.first()

    #primero llenamos la tabla de ciclos con los ciclos ya existentes
    valores_unicos = Solicitud.objects.all().order_by().values_list('ciclo', flat=True).distinct()    
    valores_unicos = list(valores_unicos)    
    valores_unicos = ordenar_lista_ciclos(valores_unicos)    
    
    for nombreCiclo in valores_unicos:
        Ciclo.objects.create(nombre=nombreCiclo, presupuesto=None)
    
    #asignar el ciclo en el campo temporal de la convocatoria
    try:
        cicloAct = Ciclo.objects.get(nombre=convocatoria.ultimo_ciclo_publicado)
        convocatoria.ultimo_ciclo_publicado_FK = cicloAct
        convocatoria.save()
    except:
        pass

    #asignar el ciclo en el campo temporal de las solicitudes
    solicitudes = Solicitud.objects.all()
    for soli in solicitudes:
        try:
            cicloSoli = Ciclo.objects.get(nombre=soli.ciclo)
            soli.ciclo_FK = cicloSoli
            soli.save()
        except:
            cicloSoli = Ciclo.objects.get(nombre='Indefinido')
            soli.ciclo_FK = cicloSoli
            soli.save()
        


    

class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0004_ciclo_hacer_presupuesto_nullable'),
        ('solicitudes', '0004_solicitud_cambiar_default_test'),
    ]

    operations = [
        migrations.RunPython(migrarDatosdeCiclos),
    ]
