# Generated by Django 4.1.7 on 2024-05-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0006_eliminar_campos_ciclo_originales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocatoria',
            old_name='ultimo_ciclo_publicado_FK',
            new_name='ultimo_ciclo_publicado',
        ),
    ]
