# Generated by Django 4.1.7 on 2024-05-07 01:18

from django.db import migrations, models
import modalidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0007_renombrar_campos_ciclo_nuevos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'ordering': ['-id'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(default=modalidades.models.ciclo_actual_genNombre, max_length=100, unique=True),
        ),
    ]
