# Generated by Django 4.1.7 on 2024-05-07 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0008_crear_funciones_ciclos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_nuevo_ciclo',
            field=models.DateField(default=datetime.date(2024, 5, 7)),
        ),
    ]
