# Generated by Django 4.1.7 on 2024-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0010_modificar_convocatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
