# Generated by Django 4.1.7 on 2024-05-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0011_modificar_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Monto')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.ciclo', verbose_name='Ciclo')),
                ('modalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidad', verbose_name='Modalidad')),
            ],
        ),
    ]
