# Generated by Django 4.1.7 on 2024-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0014_modificar_MontoModalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montomodalidad',
            old_name='modalida',
            new_name='modalidad',
        ),
        migrations.AlterUniqueTogether(
            name='montomodalidad',
            unique_together={('modalidad', 'ciclo')},
        ),
    ]
