# Generated by Django 4.1.7 on 2024-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0015_modificar_MontoModalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montomodalidad',
            options={'ordering': ['modalidad', '-id']},
        ),
        migrations.RemoveField(
            model_name='modalidad',
            name='monto',
        ),
        migrations.AddField(
            model_name='modalidad',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
