# Generated by Django 4.1.7 on 2024-05-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0016_modificar_Modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='fecha_nuevo_ciclo',
        ),
    ]
