# Generated by Django 4.1.7 on 2024-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, default='Departamento de becas COZCYT', max_length=255, null=True)),
                ('mensaje', models.TextField()),
                ('urlName', models.CharField(blank=True, max_length=255, null=True)),
                ('urlArgs', models.JSONField(blank=True, null=True)),
                ('plantilla', models.CharField(default='notificacion_default.html', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['solicitante', '-timestamp'],
            },
        ),
    ]
