# Generated by Django 4.1.7 on 2024-03-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.solicitante'),
        ),
    ]
