# Generated by Django 4.1.7 on 2024-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_test_constantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, default='Departamento de becas COZCYT', max_length=255, null=True),
        ),
    ]
